### ISSUE TITLE
Format of timestamps

### ISSUE THREAD

**Issue by chrisburr** [hev-sw/hev-sw#28]
Currently the timestamp field in the JSON broadcast messages is an integer in milliseconds. This is a problem as JSON doesn't specify what range of numbers should be supported. In Qt's JSON document parser they only support 32 bit integers causing values greater than 2^31 - 1 to be returned as 0 (as they're parsed as a double instead).

I see a few options:
1. Convert the field to a string containing a integer. This is the generally accepted solution for passing large integers in JSON in a widely compatible way.
2. Use a different JSON parser for the native interface as many others are more permissive.
3. Definite that the field to be a 32 bit integer, if so `hevserver.py` should be modified to show an error upon receiving an invalid timestamp.

I'm inclined to advocate for (1). Thoughts?

**Comment by seadanda** [comment]
The timestamps coming from the Arduino are `uint32`s, these are read exactly by the hevserver and propagated, so this won't be a problem. This is implicitly checked in the `DataFormat` struct in `CommsConstants.py` which specifies how many bytes are accepted for the timestamp from the protocol and limits this to 32 bits.

**Comment by seadanda** [comment]
Hi @chrisburr let me know if you're happy that this PR fully resolves the issue by handling the error given by any mismatches in the struct unpacking, since it's already fixed length. If you'd still rather go for 1 we could go with that also with some changes in the other UI.

**Comment by chrisburr** [comment]
Ah okay, I only saw it as I'm writing a test generator to torture-test the UI so it bypasses the unpacking.

`uint32` will still be an issue as Qt can't handle them, though we can treat them as a double without having any issues. Does the timestamp start from 0 each time chip reboots? And does it safely wrap around when it gets 2^32 (~50 days so not totally unreasonable)?

**Comment by seadanda** [comment]
Yes the wrapping is done in the Arduino. It uses `millis()` in the Arduino which is 64b, and starts at 0 at power up. When filling the payload struct, the Arduino truncates to 32b and wraps around to 0 safely if it overflows 32b. GUIs should survive timestamp resetting to 0 at any stage in case of Arduino disconnect or power cycle, so they should also be able to deal with this in the same logic.

If you want to torture-test it in a realistic way you can import the `DataFormat` class from `CommsCommon.py` and fill with a byte array of length 30 in the format defined by the toByteArray() function. Take a look at `CommsDebug` or `hevserver.py` for an example usage.

**Comment by chrisburr** [comment]
Fixed in https://gitlab.com/hev-sw/hev-display/-/merge_requests/3 by using a float for the datatype
